import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

const exportReport = ({
  metrics,
  automationRanking,
  anomalies,
}) => {
  const doc = new jsPDF();

  // Colors
  const primary = [37, 99, 235];

  const dark = [15, 23, 42];

  const gray = [100, 116, 139];

  // Header Background
  doc.setFillColor(...primary);

  doc.rect(0, 0, 220, 35, "F");

  // Title
  doc.setTextColor(255, 255, 255);

  doc.setFontSize(24);

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.text(
    "COO Automation Report",
    14,
    22
  );

  // Subtitle
  doc.setFontSize(11);

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.text(
    `Generated on ${new Date().toLocaleString()}`,
    14,
    30
  );

  // Reset Text Color
  doc.setTextColor(...dark);

  // Metrics Section
  doc.setFontSize(18);

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.text(
    "Operational Metrics",
    14,
    50
  );

  // Metric Cards
  const metricsData = [
    {
      title:
        "Recoverable Hours",
      value:
        metrics?.recoverable_hours_per_month,
    },

    {
      title:
        "Recoverable INR",
      value: `INR ${metrics?.recoverable_inr_per_month}`,
    },

    {
      title:
        "Automation Factor",
      value: `${
        metrics?.automation_factor *
        100
      }%`,
    },
  ];

  let startX = 14;

  metricsData.forEach(
    (item) => {
      doc.setFillColor(
        248,
        250,
        252
      );

      doc.roundedRect(
        startX,
        60,
        58,
        30,
        4,
        4,
        "F"
      );

      doc.setFontSize(10);

      doc.setTextColor(...gray);

      doc.text(
        item.title,
        startX + 4,
        70
      );

      doc.setFontSize(16);

      doc.setTextColor(...dark);

      doc.setFont(
        "helvetica",
        "bold"
      );

      doc.text(
        String(item.value),
        startX + 4,
        82
      );

      startX += 64;
    }
  );

  // Automation Table
  doc.setFontSize(18);

  doc.setTextColor(...dark);

  doc.text(
    "Automation Opportunities",
    14,
    110
  );

  autoTable(doc, {
    startY: 118,

    head: [
      [
        "Task",
        "Minutes",
        "Cost (INR)",
        "Score",
      ],
    ],

    body: automationRanking.map(
      (item) => [
        item.task_category,

        item.total_minutes,

        item.total_cost,

        item.automation_score,
      ]
    ),

    styles: {
      fontSize: 10,

      cellPadding: 4,
    },

    headStyles: {
      fillColor: primary,

      textColor: 255,

      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [
        248, 250, 252,
      ],
    },

    bodyStyles: {
      textColor: dark,
    },
  });

  // Anomalies
  doc.setFontSize(18);

  doc.text(
    "Employee Anomalies",
    14,
    doc.lastAutoTable.finalY + 20
  );

  autoTable(doc, {
    startY:
      doc.lastAutoTable.finalY +
      28,

    head: [
      [
        "Employee",
        "Department",
        "Severity",
      ],
    ],

    body: anomalies.map(
      (item) => [
        item.employee_name,

        item.department,

        item.severity,
      ]
    ),

    styles: {
      fontSize: 10,

      cellPadding: 4,
    },

    headStyles: {
      fillColor: [239, 68, 68],

      textColor: 255,

      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [
        248, 250, 252,
      ],
    },
  });

  // Footer
  const pageHeight =
    doc.internal.pageSize.height;

  doc.setDrawColor(
    220,
    220,
    220
  );

  doc.line(
    14,
    pageHeight - 20,
    196,
    pageHeight - 20
  );

  doc.setFontSize(10);

  doc.setTextColor(...gray);

  doc.text(
    "Generated by AI COO Automation Dashboard",
    14,
    pageHeight - 10
  );

  // Save
  doc.save(
    "coo-automation-report.pdf"
  );
};

export default exportReport;